# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-03 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjt_inventory', '0004_auto_20161003_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='product',
        ),
    ]
