# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjt_inventory', '0008_auto_20161005_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_header',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
