# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjt_inventory', '0009_auto_20161005_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='pjt_inventory.Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='pjt_inventory.Supplier'),
        ),
    ]
