# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-06 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjt_inventory', '0018_auto_20161006_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='pjt_inventory.Supplier'),
        ),
    ]
