# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-11 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjt_inventory', '0024_auto_20161007_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc_en',
            new_name='desc_body',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='tax_no',
            new_name='tax_num',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=True),
        ),
    ]
