# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-11 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjt_inventory', '0025_auto_20161011_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='pjt_inventory.Category')),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='pjt_inventory.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price_bought',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_retail',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_wholesale',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='pjt_inventory.SubCategory'),
        ),
    ]
