# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-11 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjt_inventory', '0027_auto_20161011_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='child_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pjt_inventory.Category'),
        ),
    ]
