# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjt_inventory', '0029_auto_20161014_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_flag',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Sample', 'Sample'), ('Tester', 'Tester'), ('Others', 'Others')], default='Regular', max_length=7),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.CharField(choices=[('Color', 'Color'), ('Size', 'Size'), ('Weight', 'Weight')], default='Color', max_length=7),
        ),
    ]
