# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjt_inventory', '0030_auto_20161014_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_attr', to='pjt_inventory.Product'),
        ),
    ]
