# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjt_inventory', '0034_auto_20161014_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='child_category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent_category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
