# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjt_inventory', '0035_auto_20161014_1432'),
    ]
