# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjt_inventory', '0037_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prime_category', to='pjt_inventory.CategoryDescription'),
        ),
    ]
