# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjt_inventory', '0039_auto_20161014_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pjt_inventory.Category'),
        ),
    ]
